# Generated by Django 3.1.3 on 2023-06-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230626_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='submissions',
            field=models.ManyToManyField(related_name='choices', to='onlinecourse.Submission'),
        ),
    ]
