# Generated by Django 3.1.3 on 2023-06-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230627_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='submissions',
        ),
        migrations.AddField(
            model_name='submission',
            name='choices',
            field=models.ManyToManyField(related_name='Choice', to='onlinecourse.Choice'),
        ),
    ]
